--- 

- include: repo.yml

- name: Installing InfluxDB
  apt: name=influxdb state=present

- name: Stopping InfluxDB
  service: name=influxdb state=stopped

- name: Writing configuration file
  template: src=influxdb.conf.j2 dest=/etc/influxdb/influxdb.conf

- name: Starting InfluxDB
  service: name=influxdb state=started enabled=yes

- name: Sleeping 5 seconds in order to let InfluxDB start correctly
  pause: seconds=5

- name: Creating admin account
  shell: /usr/bin/influx -execute "CREATE USER {{ influx_admin_username }} WITH PASSWORD '{{ influx_admin_password }}' WITH ALL PRIVILEGES"
  register: influx_create_admin
  failed_when: influx_create_admin.rc != 0
  ignore_errors: true

- name: Creating metrics user
  shell: /usr/bin/influx -username "{{ influx_admin_username }}" -password "{{ influx_admin_password }}" -execute "CREATE USER {{ influx_metrics_username }} WITH PASSWORD '{{ influx_metrics_password }}'"
  register: influx_create_user
  failed_when: influx_create_user.rc != 0


- name: Creating metrics database
  shell: /usr/bin/influx -username "{{ influx_admin_username }}" -password "{{ influx_admin_password }}" -execute "CREATE DATABASE {{ influx_metrics_database }}"
  register: influx_create_database
  failed_when: influx_create_database.rc != 0

- name: Setting up retention for the database
  shell: /usr/bin/influx -username "{{ influx_admin_username }}" -password "{{ influx_admin_password }}" -execute "CREATE RETENTION POLICY twoweeks ON {{ influx_metrics_database }} DURATION 15d REPLICATION 1 DEFAULT"
  register: influx_set_retention
  failed_when: influx_set_retention.rc != 0

- name: Adding user permissions to the database
  shell: /usr/bin/influx -username "{{ influx_admin_username }}" -password "{{ influx_admin_password }}" -execute "GRANT ALL ON {{ influx_metrics_database }} TO {{ influx_metrics_username }}"
  register: influx_set_user_to_db
  failed_when: influx_set_user_to_db.rc != 0


