---

- name: Installing https transport for apt
  apt: name=apt-transport-https state=present

- name: Importing InfluxDB GPG signing key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present

- name: Adding InfluxDB repository
  apt_repository: repo="deb https://repos.influxdata.com/ubuntu {{ ansible_distribution_release }} stable" state=present

- name: Refreshing package list
  apt: update_cache=yes

